name: Build Archlinux Packages

on:
  push:
    branches:
      - main
  workflow_dispatch: # allow manual trigger


jobs:
  Build: # build packages
    strategy:
      matrix:
        pkg: [ 
        aseprite,
        ladybird-git
        ]
      fail-fast: false # allow package build fails
    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
      - name: Update system base
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm git
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Bump submodules
        run: |
          git config --global --add safe.directory /__w/aurbuild/aurbuild
          git submodule update --init --remote

      - name: Build package
        run: |
          cd ${{ matrix.pkg }}
          chmod a+rwx .
          export MAKEFLAGS="--jobs=$(nproc)"
          runuser -m -u nobody -- makepkg -s

      - name: Upload to release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          tag: "packages"
          artifacts: "./*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}
