name: Build Archlinux Packages

on:
  #push:
  #  branches:
  #    - master
  workflow_dispatch: # allow manual trigger


jobs:
  Build: # build packages
    strategy:
      matrix:
        pkg: [ 
        aseprite,
        ladybird-git
        ]
    fail-fast: false # allow package build fails
    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
      - name: Update system base
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm git
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Bump submodules
        run: |
          git submodule update --init --remote

      - name: Build package
        run: |
          cd ${{ matrix.pkg }}
          makepkg -s

      - name: Upload to release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          tag: "packages"
          artifacts: "./*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}
