name: Build Archlinux Packages

on:
  workflow_dispatch: # allow manual trigger


jobs:
  Build: # build packages
    strategy:
      matrix:
        pkg: [ 
        ares-emu,
        aseprite,
        ladybird-git
        ]
      fail-fast: false # allow package build fails
    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
      - name: Update system base and expected provider depends
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm base-devel git
          pacman -S --noconfirm vulkan-intel
          echo 'nobody ALL=(ALL:ALL) NOPASSWD: ALL' > /etc/sudoers.d/nobody
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Bump submodules
        run: |
          git config --global --add safe.directory /__w/aurbuild/aurbuild
          git submodule update --init --remote

      - name: Build package
        run: |
          cd ${{ matrix.pkg }}
          chmod a+rwx .
          export MAKEFLAGS="--jobs=$(nproc)"
          runuser -m -u nobody -- makepkg -s --noconfirm

      - name: Upload to release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          tag: "packages"
          artifacts: "./*/*.zst,./*/*.sig"
          token: ${{ secrets.GITHUB_TOKEN }}
